# intro to tensors and tensor operations in pytorch


In [1]:
import torch
import numpy as np

initializing a tensor

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3030, 0.4923],
        [0.0688, 0.3427]]) 



In [5]:
shape = (1,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2732, 0.5569, 0.8851]]) 

Ones Tensor: 
 tensor([[1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.]])


properties of a tensor

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


switching to an accelerator instead of cpu

In [7]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(tensor.device)

cuda:0


tensor operations

In [8]:
tensor = torch.ones(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


arithmetic operations

In [10]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(f"y1: {y1}")
print(f"y2: {y2}")
print(f"y3: {y3}")
print()

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f"z1: {z1}")
print(f"z2: {z2}")
print(f"z3: {z3}")

y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
agg = tensor.sum()
print(agg.item(), type(agg.item()))

92.0 <class 'float'>


In [16]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


Bridge with NumPy:
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [19]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [20]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


create vectors <br> create matrices <br> perform matrix multiplication <br> reshape tensors <br> transpose them <br> compute mean <br> compute sum <br> compute max <br> generate random tensors

In [21]:
# Scalar (0D tensor)
scalar = torch.tensor(7)
print("Scalar:")
print(scalar)
print("Shape:", scalar.shape)

# Vector (1D tensor)
vector = torch.tensor([1, 2, 3, 4, 5])
print("\nVector:")
print(vector)
print("Shape:", vector.shape)

# Matrix (2D tensor)
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nMatrix:")
print(matrix)
print("Shape:", matrix.shape)

Scalar:
tensor(7)
Shape: torch.Size([])

Vector:
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [23]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# Matrix multiplication
C = torch.matmul(A, B)

print("A @ B =")
print(C)

Matrix A:
 tensor([[1, 2],
        [3, 4]])

Matrix B:
 tensor([[5, 6],
        [7, 8]])
A @ B =
tensor([[19, 22],
        [43, 50]])


In [24]:
#can also do this
C = A @ B
print(C)

tensor([[19, 22],
        [43, 50]])


In [25]:
tensor = torch.arange(12)

print("Original:")
print(tensor)
print("Shape:", tensor.shape)

reshaped = tensor.reshape(3, 4)

print("\nReshaped:")
print(reshaped)
print("Shape:", reshaped.shape)

Original:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Reshaped:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])


In [26]:
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original:")
print(matrix)

print("\nTranspose:")
print(matrix.T)

Original:
tensor([[1, 2, 3],
        [4, 5, 6]])

Transpose:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [31]:
values = torch.tensor([10., 20., 30., 40., 50.])

print("Values:", values)
print("Mean:", values.mean())
print("Sum:", values.sum())
print("Maximum:", values.max())
print("Index of max:", values.argmax())

Values: tensor([10., 20., 30., 40., 50.])
Mean: tensor(30.)
Sum: tensor(150.)
Maximum: tensor(50.)
Index of max: tensor(4)


In [32]:
random_tensor = torch.rand(3, 4)

print(random_tensor)

tensor([[0.5702, 0.9828, 0.6333, 0.8726],
        [0.3901, 0.9039, 0.3516, 0.3554],
        [0.1308, 0.0955, 0.9841, 0.9669]])


In [33]:
random_ints = torch.randint(
    low=0,
    high=10,
    size=(3, 4)
)

print(random_ints)

tensor([[8, 0, 9, 8],
        [5, 9, 4, 6],
        [3, 5, 3, 3]])


In [34]:
#rand from a normal distribution
random_normal = torch.randn(3, 4)

print(random_normal)

tensor([[ 4.9809e-01, -2.0530e+00, -8.0717e-01,  3.0942e-01],
        [ 1.7335e+00, -8.4682e-01,  2.0011e-03,  1.0392e+00],
        [-6.5212e-01,  1.1131e+00,  6.6269e-01, -5.5168e-01]])


In [35]:
print("Zeros:")
print(torch.zeros(2, 3))

print("\nOnes:")
print(torch.ones(2, 3))

print("\nIdentity Matrix:")
print(torch.eye(4))

print("\nSequence:")
print(torch.arange(0, 10))

print("\nEvenly spaced values:")
print(torch.linspace(0, 1, 5))

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Identity Matrix:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Sequence:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Evenly spaced values:
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [36]:
tensor = torch.rand(3, 4)

print(tensor)

print("Shape :", tensor.shape)
print("Dimensions :", tensor.ndim)
print("Data type :", tensor.dtype)
print("Device :", tensor.device)

tensor([[0.9575, 0.8815, 0.7397, 0.5218],
        [0.6978, 0.8163, 0.6731, 0.8242],
        [0.2305, 0.6103, 0.5355, 0.0569]])
Shape : torch.Size([3, 4])
Dimensions : 2
Data type : torch.float32
Device : cpu
